jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Use Node.js 18.x
      uses: actions/setup-node@master
      with:
        node-version: 18.x
    - continue-on-error: true
      name: install danger
      run: yarn global add danger
    - continue-on-error: true
      name: Validate PR title validation rules
      run: node validate.test.js
      working-directory: ./ci/validate-pr-title
    - continue-on-error: true
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}
      name: Danger
      run: danger ci
      working-directory: ./ci/validate-pr-title
name: Danger
on:
  repository_dispatch:
    types: trigger-ga___danger.yml
